name: Auto-issuing.js CI

on: [push]

jobs:
  auto-create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            filename: issues.md